config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    has_many :tasks

    validate :title_length
    validate :startdate_validation  
    validate :finishdate_validation
    validate :date_validation


    def title_length
        if title.empty?
            errors[:base] << "タイトルを20文字以内で入力してください"
        end

        if title.length > 20
            errors[:base] << "タイトルは20文字以内で入力してください"
        end

    end

    def startdate_validation
        if startdate == nil
            errors[:base] << "開始日を入力してください"
        end
    end

    def finishdate_validation
        if finishdate == nil
            errors[:base] << "終了日を入力してください"
        end
    end

    def date_validation
        if startdate == nil || finishdate == nil
            return
        end

        if startdate > finishdate
            errors[:base] << "終了日は、開始日かそれ以降を指定してください"
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]


  
  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
    @counts = Task.count
    @today = Date.today.strftime('%Y年%m月%d日')
  end


  # GET /tasks/1 or /tasks/1.json
  def show
    @today = Date.today.strftime('%Y年%m月%d日')
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @today = Date.today.strftime('%Y年%m月%d日')
  end

  # GET /tasks/1/edit
  def edit
    @today = Date.today.strftime('%Y年%m月%d日')
  end

  # POST /tasks or /tasks.json
  def create
    @today = Date.today.strftime('%Y年%m月%d日')
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "スケジュールを登録しました" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "スケジュールを更新しました" }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end

    @today = Date.today.strftime('%Y年%m月%d日')
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "スケジュールを削除しました" }
      format.json { head :no_content }
    end
    @today = Date.today.strftime('%Y年%m月%d日')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
      @today = Date.today.strftime('%Y年%m月%d日')
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :startdate, :finishdate, :allday, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><% pluralize(task.errors.count, "error") %> 以下のエラーがあります。。。</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<table>
 <tbody>
  <tr>
    <div class="field">
    <th><%= form.label :'タイトル' %></th>
    <td><%= form.text_field :title %></td>
    </div>
  </tr>

  <tr>
    <div class="field">
    <th><%= form.label :'開始日' %></th>
    <td><%= form.date_field :startdate %></td>
    </div>
  </tr>

  <tr>
  <div class="field">
    <th><%= form.label :'終了日' %></th>
    <td><%= form.date_field :finishdate %></td>
   </div>
  </tr>

  <tr>
  <div class="field">
    <th><%= form.label :'終日' %></th>
    <td><%= form.check_box :allday %><br>
    <%= '終日の場合はチェックを入れます' %></td>
   </div>
  </tr>

  <tr>
   <div class="field">
       <th><%= form.label :'スケジュールメモ' %></th>
       <td><%= form.text_area :memo %></td>
   </div>
  </tr> 

 </tbody>
 </table>

  <div class="actions">
    <%= form.submit('スケジュールの編集を完了する', :class=>'fbtn') %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<body>

 <header>
   <h1>Ruby on Rails スケジュール管理アプリ</h1>
 </header>

 <div class = "main_container">
     <div class = "information">
       <h2>スケジュール編集</h2>
     </div>

       <%= render 'form', task: @task %>

       <%= link_to 'スケジュール一覧に戻る', tasks_path %>
       
  </div>

 <footer>
  <h1>現在の日時：<%= @today %></h1>
 </footer>

</body>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<body>
 <header>
  <h1>Ruby on Rails スケジュール管理アプリ</h1>
 </header>

 <div class="main_container">
  <div clas="information">
 <h2>スケジュール一覧</h2>
  </div>

 <table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>スケジュール更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.id %></td>
        <td><%= task.title %></td>
        <td><%= task.startdate %></td>
        <td><%= task.finishdate %></td>
        　　<% if task.allday == true %>
        <td> ○  </td>
          　<% else task.allday == false %>
        <td>　</td>
            <% end %>
        <td><%= task.updated_at %></td>
        <td><%= link_to '確認', task %></td>
        <td><%= link_to '編集', edit_task_path(task) %></td>
        <td><%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
 </table>

 <br>

 <%= link_to 'スケジュール新規登録', new_task_path %>

</div>
 <footer>
  <h1>現在の日時：<%= @today %> スケジュール合計：<%= @counts %></h1>
 </footer>

</body>

app/views/tasks/new.html.erb
<body>
 <header>
  <h1>Ruby on Rails スケジュール管理アプリ</h1>
 </header>
 <div class="main_container">
  <div class="information">
   <h2>スケジュール新規作成</h2>
  </div>

  <%= render 'form', task: @task %>

  <%= link_to 'スケジュール一覧に戻る', tasks_path %>

 </div>
 <footer>
  <h1>現在の日時：<%= @today %></h1>
 </footer>
</body>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<body>
 <header>
  <h1>Ruby on Rails スケジュール管理アプリ</h1>
 </header>

 <div class = "main_container">
    <div class = "information">
     <h2>スケジュール詳細</h2>
    </div>

   <table>
   <tbody>
    <tr>
     <th>タイトル</th>
     <td><%= @task.title %></td>
    </tr>

    <tr>
     <th>開始日</th>
     <td><%= @task.startdate %></td>
    </tr>

    <tr>
     <th>終了日</th>
     <td><%= @task.finishdate %></td>
    </tr>

 
    <tr>
      <th>終日</th>  
      <% if @task.allday == true%>
          <td>○</td>
        　<%else @task.allday == false%>
          <td> </td>
          <% end %>
    </tr>


    <tr>
      <th>メモ</th>
      <td><%= @task.memo %></td>
    </tr>
    </tbody>
   </table>

   <%= link_to 'スケジュールを編集する', edit_task_path(@task) %> |
   <%= link_to 'スケジュール一覧に戻る', tasks_path %>

  </div>

 <footer>
  <h1>現在の日時：<%= @today %></h1>
 </footer>

 </body>